// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTerminalLogs() {
  return window['go']['main']['App']['ClearTerminalLogs']();
}

export function ClearTerminalLogsByID(arg1) {
  return window['go']['main']['App']['ClearTerminalLogsByID'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateLocalTerminal(arg1) {
  return window['go']['main']['App']['CreateLocalTerminal'](arg1);
}

export function CreateSSHTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSSHTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSSHTerminalWithKey(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateSSHTerminalWithKey'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteTerminalUser(arg1) {
  return window['go']['main']['App']['DeleteTerminalUser'](arg1);
}

export function ExecuteTerminalCommand(arg1) {
  return window['go']['main']['App']['ExecuteTerminalCommand'](arg1);
}

export function ExecuteTerminalCommandByID(arg1, arg2) {
  return window['go']['main']['App']['ExecuteTerminalCommandByID'](arg1, arg2);
}

export function GetCurrentTerminalUser() {
  return window['go']['main']['App']['GetCurrentTerminalUser']();
}

export function GetTerminalLogs(arg1) {
  return window['go']['main']['App']['GetTerminalLogs'](arg1);
}

export function GetTerminalLogsByID(arg1, arg2) {
  return window['go']['main']['App']['GetTerminalLogsByID'](arg1, arg2);
}

export function ListCaptureInterfaces() {
  return window['go']['main']['App']['ListCaptureInterfaces']();
}

export function ListTerminalUsers() {
  return window['go']['main']['App']['ListTerminalUsers']();
}

export function ListTerminals() {
  return window['go']['main']['App']['ListTerminals']();
}

export function ResizeTerminalByID(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminalByID'](arg1, arg2, arg3);
}

export function ServiceStatus() {
  return window['go']['main']['App']['ServiceStatus']();
}

export function SetCaptureInterface(arg1, arg2) {
  return window['go']['main']['App']['SetCaptureInterface'](arg1, arg2);
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StartCaptureWithInterface(arg1, arg2) {
  return window['go']['main']['App']['StartCaptureWithInterface'](arg1, arg2);
}

export function StartEmbeddedStack() {
  return window['go']['main']['App']['StartEmbeddedStack']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}

export function StopEmbeddedStack() {
  return window['go']['main']['App']['StopEmbeddedStack']();
}

export function TerminalLogin(arg1, arg2) {
  return window['go']['main']['App']['TerminalLogin'](arg1, arg2);
}

export function UpsertTerminalUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpsertTerminalUser'](arg1, arg2, arg3, arg4);
}

export function WriteTerminalInputByID(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminalInputByID'](arg1, arg2);
}
