// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearTerminalLogs():Promise<boolean>;

export function ClearTerminalLogsByID(arg1:string):Promise<boolean>;

export function CloseTerminal(arg1:string):Promise<boolean>;

export function CreateLocalTerminal(arg1:string):Promise<main.TerminalInfo>;

export function CreateSSHTerminal(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<main.TerminalInfo>;

export function DeleteTerminalUser(arg1:string):Promise<boolean>;

export function ExecuteTerminalCommand(arg1:string):Promise<string>;

export function ExecuteTerminalCommandByID(arg1:string,arg2:string):Promise<string>;

export function GetCurrentTerminalUser():Promise<Record<string, string>>;

export function GetTerminalLogs(arg1:number):Promise<Array<main.TerminalEntry>>;

export function GetTerminalLogsByID(arg1:string,arg2:number):Promise<Array<main.TerminalEntry>>;

export function ListCaptureInterfaces():Promise<Array<main.CaptureInterface>>;

export function ListTerminalUsers():Promise<Array<Record<string, any>>>;

export function ListTerminals():Promise<Array<main.TerminalInfo>>;

export function ServiceStatus():Promise<Record<string, any>>;

export function SetCaptureInterface(arg1:number,arg2:string):Promise<Record<string, any>>;

export function StartCapture():Promise<Record<string, any>>;

export function StartCaptureWithInterface(arg1:number,arg2:string):Promise<Record<string, any>>;

export function StartEmbeddedStack():Promise<Record<string, any>>;

export function StopCapture():Promise<Record<string, any>>;

export function StopEmbeddedStack():Promise<Record<string, any>>;

export function TerminalLogin(arg1:string,arg2:string):Promise<Record<string, string>>;

export function UpsertTerminalUser(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;
